### ISSUE TITLE
E32-91520D with SX1276

### ISSUE THREAD

**Issue by JRAlvarez2017** [KrisKasprzak/EBYTE#10]
Is it possible to communicate a ES32-91520D with a SX1276 (SPI interface with Arduino)? 
Do we know the LoRa settings in the ES32-91520D?

**Comment by masc-it** [comment]
same here, any news @JRAlvarez2017 ?

**Comment by KrisKasprzak** [comment]
I don't see why you can't communicate back and forth using that configuration. From the data sheet you have to be on the same channel, air data rate, and address (if not using address 0xFFFF or 0x0000.
I have this same transceiver communicating between and Arduino and a Teensy 3.2. My lib has updated example code

**Comment by masc-it** [comment]
`EBYTE Transceiver(&Serial1, 5, 4, 3);
void setup() {

  Serial.begin(9600);
  Serial1.begin(9600);

  pinMode(5, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(3, INPUT);

  Transceiver.init();


  Transceiver.SetChannel(6); // 862 + 6 = 868 in my case
  Transceiver.SetAddress(0x0000);
  Transceiver.SaveParameters(TEMPORARY);
    Transceiver.PrintParameters();
   

}
`
Then in the loop I check if data is available, but nothing.
(the sender is an Heltec v2, LoRa based on sx1276 868mhz)

**Comment by KrisKasprzak** [comment]
note this library is only for UART based devices not the SPI ones EBYTE offers

**Comment by renanqts** [comment]
@masc-it did you find a solution for this?

**Comment by masc-it** [comment]
@renanqts check this other [ebyte library ](https://github.com/xreef/LoRa_E32_Series_Library)

**Comment by yachal-upson** [comment]
:Bump:
Also really interested in this. 
I rebooted on a project where I'd bought a number of ES32 modules (really easy implementation among themselves).
However I'm trying to achieve communication between a number of Heltec AB01 Cubecells and an ES32 as a base station. 

Can't for the life of me understand what the settings + address etc needs to be; Ebyte have done so much 'under the hood', that isn't plain SX1276. 

Are the ES32's implementing encryption by default? Will they accept packets/frames without Ebyte proprietary headers etc?

**Comment by varna9000** [comment]
I'm also interested if e32 modules can communicate with other non ebyte modules (e.g. plain sx126x/sx127x). Is there any settings besides the appended header of address + channel bytes?

**Comment by KrisKasprzak** [comment]
I've never experimented with non CBYTE modules based on the same chip. I'm not sure if this lib would support other mfg's. If you have a module in mind, post a link and i'll look at it's datasheet.
