### ISSUE TITLE
Set Parameters Missing

### ISSUE THREAD

**Issue by srcamarda** [KrisKasprzak/EBYTE#12]
The functions to set the three parameters below are missing:

_OptionTrans
_OptionPullup
_OptionFEC

I added the functions in EBYTE.cpp / EBYTE.h and it worked perfectly for my use, but maybe you should add it to your code.

**Comment by AB-informatica-service** [comment]
Can you post the functions that you have write? Thanks

**Comment by KrisKasprzak** [comment]
I don't understand what you are asking. 
Thanks,
Kris Kasprzakkris.kasprzak@yahoo.com
 

    On Saturday, February 29, 2020, 11:02:59 AM CST, AB-informatica-service <notifications@github.com> wrote:  
 
 
Can you post the functions that you have write? Thanks

**Comment by srcamarda** [comment]
There's my modified files [EBYTE.zip](https://github.com/KrisKasprzak/EBYTE/files/4277496/EBYTE.zip)

If I remember well (not really sure), I simply added this on EBYTE.cpp:

`void EBYTE::SetTrans(uint8_t val) {
	_OptionTrans = val;
	BuildOptionByte();
}`

`void EBYTE::SetPullup(uint8_t val) {
	_OptionPullup = val;
	BuildOptionByte();
}`

`void EBYTE::SetFEC(uint8_t val) {
	_OptionFEC = val;
	BuildOptionByte();
}`

And this to EBYTE.h (in class EBYTE):

`	void SetTrans(uint8_t val);
	void SetPullup(uint8_t val);
	void SetFEC(uint8_t val);`

The variables and significant info were already there, there just wasn't a way to modify them.

**Comment by KrisKasprzak** [comment]
these functions and more added
