### ISSUE TITLE
Set Sync word

### ISSUE THREAD

**Issue by masc-it** [KrisKasprzak/EBYTE#15]
How can we set the sync word? There is no available method.

**Comment by KrisKasprzak** [comment]
sync word? I don't recall seeing this in the data sheet. If you can point me to the documentation, i'll look at adding the methods

**Comment by masc-it** [comment]
You can't find anything related to it in the docs, but it's a parameter that SX1276 allows to change, and I didn't find a correspective in the EBYTE docs. Thought you knew something about this.
I am trying to make communicate a sx1276 (heltec lora v2) with an EBYTE 868T30D, and air data rate, parity bit and sync word must be the same. The problem is that: I can't find air data rate nor parity bit specs on the heltec and nothing about sync word on the EBYTE. 
Do you have any tips? I'm kinda out of ideas right now.

**Comment by clabnet** [comment]
+1, same issue.

**Comment by renanqts** [comment]
@masc-it did you find a solution for this?

**Comment by ivanboesing** [comment]
+2, same issue

**Comment by luccareinehr** [comment]
+3

Maybe it has something to do with the address mentioned in EBYTE's datasheet?

**Comment by masc-it** [comment]
I tried them all, no solutions. Eventually I bought another EBYTE card and used LoRa_E32_Series_Library by xreef. If you want I can share some setup code :)

**Comment by karfam** [comment]
> EBYTE card a

Hello Sir
if possible share some code.

**Comment by KrisKasprzak** [comment]
what do you need that is different from the examples?
Thanks,
Kris Kasprzak
 

    On Friday, January 7, 2022, 10:13:07 AM CST, karfam ***@***.***> wrote:  
 
 



EBYTE card a


Hello Sir
if possible share some code.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by karfam** [comment]
> what do you need that is different from the examples? Thanks, Kris Kasprzak On Friday, January 7, 2022, 10:13:07 AM CST, karfam ***@***.***> wrote: EBYTE card a Hello Sir if possible share some code. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

Good Morning Kris
Sorry for my misunderstanding. 
I thought @masc-it  had some code so that EBYTE module can transmit a message a different Lora module manufacturer like TTGO-TBEAM.
But this is not case here :)

I have found some settings between EBYTE air data rate and Lora Settings but still no luck

0.3kbps - SF: 12 BW: 7 CR: 1
1.2kbps - SF: 11 BW: 8 CR: 1
2.4kbps - SF: 11 BW: 9 CR: 1
4.8kbps - SF: 8 BW: 8 CR: 2
