### ISSUE TITLE
Configuration Problem

### ISSUE THREAD

**Issue by luisme** [KrisKasprzak/EBYTE#2]
Good Morning,
I'm doing a project for university, and I'm using 2 Transceivers Ebyte E32-868T30D.

I can communicate up to a distance of 10/15 meters but more than that.

Can you give me some help in configuring them !?

**Comment by KrisKasprzak** [comment]
what antennas are you using? how far off the ground are the antennas? what's the transmit power, what's the transmit air data rate? what MCU's how much data are you trying to send? Not much I can do w/o knowing the basic info.
