### ISSUE TITLE
Does the E32/E22 UART expose enough functionality to implement LoRaWAN?

### ISSUE THREAD

**Issue by avillacis** [KrisKasprzak/EBYTE#23]
Hello. I am studying your library as part of an IoT project involving an Espressif ESP32 using an EBYTE E22-900T30S chip for communication. I am aware of the command set difference talked about in #20 , as well as confirmed it, and I was intending to use this library as a starting point for the project. However, the catch is that the project involves communication with a LoRaWAN gateway. Now, I am aware that the EBYTE E22 series speaks the LoRa radio protocol but does not, by itself, implement the LoRaWAN stack at all. On the other hand, I have found a few libraries that purport to implement LoRaWAN, such as https://github.com/beegee-tokyo/SX126x-Arduino . On this library, for example, the tested chip is an E22-900M22S that is controlled over SPI and appears to have more options.

The basic question is: is the lack of LoRaWAN support something that can be fixed in software by using a LoRaWAN stack and plugging it into the E22 UART interface? Or does the E32/E22 UART interface isolate the programmer from the radio link to the point that speaking LoRaWAN is impossible? What do I need to know about the LoRaWAN stack to find out?

**Comment by KrisKasprzak** [comment]
The manufacture of the Ebyte transceiver does not expose this functionality. I am not even sure this capability is available with the ship 3 using
