### ISSUE TITLE
return 0 value problem 

### ISSUE THREAD

**Issue by aliustunelin** [KrisKasprzak/EBYTE#25]
First of all, thank you for your stable work. I'm working with arduino nano. There is no problem in getting the value, but after a while, arduino nano: 26th value, value is uno: 40th value. nano always return 0.
What could be the reason for this?

**Comment by KrisKasprzak** [comment]
I just Uploaded a version that may have fixed this issue. I can't reproduce it but I put some extra code and declare buffers in such. Could you download the latest version in give it a try?
