### ISSUE TITLE
Possible bug, passing the address of an address

### ISSUE THREAD

**Issue by abusous2000** [KrisKasprzak/EBYTE#26]
Hi Kris,

Many thank for a simple and powerful library.
As I was code reviewing your work, i came across this line of code in method **bool EBYTE::ReadModelData()**
__s->readBytes((uint8_t*)**&** _Params, (uint8_t) sizeof(_Params));_

I suspect this is wrong since it passes the address of the buffer pointer. Ichanged it to
_bool EBYTE::ReadModelData()_s->readBytes((uint8_t*) _Params, (uint8_t) sizeof(_Params));_

For some reason; it gave me the same data back. May be the compiler did some optimization.

peace

**Comment by KrisKasprzak** [comment]
I think you need to cast address of the struct-object, not the struct-object itself.
