### ISSUE TITLE
Programming mode - baud rate limitation?

### ISSUE THREAD

**Issue by vindolin** [KrisKasprzak/EBYTE#28]
@KrisKasprzak Thank you for the inspiration, 
After finishing an ESP32 LoRa to MQTT gateway with your library, I started working on a similar library for Python on a RaspberryPi (GPIO header).

https://github.com/vindolin/python_ebyte_lora

When reading the Ebyte datasheet for the E32-868T20D module, I noticed that it reads:

![image](https://user-images.githubusercontent.com/834347/93901491-dd1c5f80-fcf6-11ea-8b98-fc220cdc0e94.png)

Do the older modules allow programming in different baud rates?

Cheers
Thomas

**Comment by KrisKasprzak** [comment]
My experience with these goes back about 4 years metal ever remember seeing older units supporting anything other than 9600
