### ISSUE TITLE
How can i check if the packet is well received or not?

### ISSUE THREAD

**Issue by hope-miky** [KrisKasprzak/EBYTE#29]
I really appreciate your work, It helped me a lot in my project. I wanted to check if my data has been received or not by the receiver. How can do this using your library or is there any other way to implement this?

**Comment by KrisKasprzak** [comment]
I always send data via a structure so when the receiver gets a struct you will have all the data. 
 

    On Saturday, October 3, 2020, 02:45:42 PM CDT, Tesfamichael <notifications@github.com> wrote:  
 
 


I really appreciate your work, It helped me a lot in my project. I wanted to check if my data has been received or not by the receiver. How can do this using your library or is there any other way to implement this?
