### ISSUE TITLE
Unable to set parameters and print them?? 

### ISSUE THREAD

**Issue by hussainkadori** [KrisKasprzak/EBYTE#31]
Hi,
I used two E22-900T30S modules with two Arduino Uno. Modules send and receive data without any problem except setting and printing the parameters?

How to solve this?

**Comment by KrisKasprzak** [comment]
I just Uploaded a version that may have fixed the print parameter issue you are seeing. Could you download it and try again? I have not been able to reproduce this issue

**Comment by KrisKasprzak** [comment]
considering this now working.
