### ISSUE TITLE
Сommunication between ebyte E22 uart and spi modules.

### ISSUE THREAD

**Issue by LoginovSerg** [KrisKasprzak/EBYTE#32]
Hi,
I have an ebyte e22-400t30d module. This module is based on sx1268 chip and has uart interface. It's easy to program, but there is no access to the sx1268 chip settings. I want to establish communication between this module and another one based on the sx1278 chip and having a spi interface. Does anyone know what parameters the ebyte e22-400t30d uses? I need to know Modulation BandWidth, Spreading Factor, Coding Rate and others.

**Comment by KrisKasprzak** [comment]
I would recommend sending this question to the manufacturer. If both modules are set to the same air data rate, channel, address. the should communicate. Maybe indicate what the other module is.

A contact at EBYTE: 
sales07@ebyte.com
sales06@ebyte.com
zengyao@cdebyte.com
