### ISSUE TITLE
Sender send only 1 packet

### ISSUE THREAD

**Issue by Lucamenghini** [KrisKasprzak/EBYTE#38]
Hi, I'm working with ESP32. The sender sends only the first packet. If i put one more supply from an out source (5v 2.5A power supplier ) and supply with it only the E32-868T30D the problem it's the same. When i detach the E32 power supply and reattach it it sends only the first packet (seen on a receiver, an other ESP32 with another E32-868T30D).
what could be the problem?
thank you in advance
LucaM

**Comment by KrisKasprzak** [comment]
not much for me to go on here. no wiring diagram, not code. nothing.
