### ISSUE TITLE
problems running an D1 mini 

### ISSUE THREAD

**Issue by UweW** [KrisKasprzak/EBYTE#4]
Hi,
I need some help I can't get the code running .
I have a wemos D1 mini version 2.2.0 and a E32-868T20D.
In the first step I try to send out something and check with a rtl_sdr stick if the E32 is sending something.
I am wondering that I do not see any parameters (all zero). Maybe the cabling is not correct I also do not see any thing on 868 MHz. The E32 is preconfigured on channel 10.
 
Serial output 
14:16:43.836 -> 2dO,4⸮$48⸮lb8⸮⸮⸮Starting Sender
14:16:46.552 -> ----------------------------------------
14:16:46.585 -> Model no.: 0
14:16:46.585 -> Version  : 0
14:16:46.619 -> Features : 0
14:16:46.619 ->  
14:16:46.619 -> Mode (HEX/DEC/BIN): 0/0/0
14:16:46.652 -> AddH (HEX/DEC/BIN): 0/0/0
14:16:46.685 -> AddL (HEX/DEC/BIN): 0/0/0
14:16:46.718 -> Sped (HEX/DEC/BIN): 0/0/0
14:16:46.751 -> Chan (HEX/DEC/BIN): 0/0/0
14:16:46.751 -> Optn (HEX/DEC/BIN): 0/0/0
14:16:46.784 -> Addr (HEX/DEC/BIN): 0/0/0
14:16:46.817 ->  
14:16:46.817 -> SpeedParityBit (HEX/DEC/BIN)    : 0/0/0
14:16:46.884 -> SpeedUARTDataRate (HEX/DEC/BIN) : 0/0/0
14:16:46.917 -> SpeedAirDataRate (HEX/DEC/BIN)  : 0/0/0
14:16:46.950 -> OptionTrans (HEX/DEC/BIN)       : 0/0/0
14:16:46.983 -> OptionPullup (HEX/DEC/BIN)      : 0/0/0
14:16:47.083 -> OptionWakeup (HEX/DEC/BIN)      : 0/0/0
14:16:47.083 -> OptionFEC (HEX/DEC/BIN)         : 0/0/0
14:16:47.149 -> OptionPower (HEX/DEC/BIN)       : 0/0/0
14:16:47.182 -> ----------------------------------------

cabeling
D1 mini       E32
3,3V   --  VCC
G  -- GND
D2 -- M0
D1 -- M1 
RX  -- TX
TX -- RX
D5 -- AUX

code 
#include <SoftwareSerial.h>
#include "EBYTE.h"

#define PIN_M0 4  // Wemos D1 mini = D2
#define PIN_M1 5  // Wemos D1 mini = D1
#define PIN_AX 14  // Wemos D1 mini = D5 
..
.
SoftwareSerial ESerial(1, 3);
EBYTE Transceiver(&ESerial, 4, 5, 14);
.................

Hope that somebody can help

**Comment by KrisKasprzak** [comment]
1. are you sure about the pins for RX TX?
2. are the pins 3v3 or 5v0 if 5v0,  you may need 4k7 resistors in series with RX and/or Tx
3. code never tested with Wemos
4. measure voltage on M0 M1 and make sure they are getting set? You sure they are pin 4 and 5?
