### ISSUE TITLE
Support for Ebyte SPI modules

### ISSUE THREAD

**Issue by FlorianBogeschdorfer** [KrisKasprzak/EBYTE#42]
I want to use the LoRaWAN module 868LN22S. Would it be supported? I am not perfectly clear if this module supports UART or SPI, web sources are not clear about it.  Thank you!

**Comment by KrisKasprzak** [comment]
Have a look at the first sentence in the library description

"This library is intended to be used with UART type EBYTE transceivers (E44-TTL-100 for example), ..."
