### ISSUE TITLE
Receiving 1 packet yes and 1 not

### ISSUE THREAD

**Issue by Lucamenghini** [KrisKasprzak/EBYTE#47]
Hi! Thank you for your great work!

Using Send & Receive examples i receive 1 packet yes and 1 not.
In the example below you can see the counter 248, 250, 252, 254, 256, 258 ....
The parameters for both sender & receiver are the same:
----------------------------------------
Model no.: 0
Version  : 45
Features : 32
 
Mode (HEX/DEC/BIN): C0/192/11000000
AddH (HEX/DEC/BIN): 0/0/0
AddL (HEX/DEC/BIN): 0/0/0
Sped (HEX/DEC/BIN): 1A/26/11010
Chan (HEX/DEC/BIN): F/15/1111
Optn (HEX/DEC/BIN): 44/68/1000100
Addr (HEX/DEC/BIN): 0/0/0
 
SpeedParityBit (HEX/DEC/BIN)    : 0/0/0
SpeedUARTDataRate (HEX/DEC/BIN) : 3/3/11
SpeedAirDataRate (HEX/DEC/BIN)  : 2/2/10
OptionTrans (HEX/DEC/BIN)       : 0/0/0
OptionPullup (HEX/DEC/BIN)      : 1/1/1
OptionWakeup (HEX/DEC/BIN)      : 0/0/0
OptionFEC (HEX/DEC/BIN)         : 1/1/1
OptionPower (HEX/DEC/BIN)       : 0/0/0
----------------------------------------

and this is the receive result:

Receiving: 248 ,18.20 °C, 63.02 %U, Uuid: ⸮R<x⸮⸮K⸮%
Searching: 
218175
Receiving: 250 ,18.20 °C, 63.05 %U, Uuid: ⸮R<x⸮⸮K⸮%
Searching: 
220218
Receiving: 252 ,18.19 °C, 63.16 %U, Uuid: ⸮R<x⸮⸮K⸮%
Searching: 
222338
Receiving: 254 ,18.19 °C, 63.20 %U, Uuid: ⸮R<x⸮⸮K⸮%
Searching: 
224358
Receiving: 256 ,18.16 °C, 63.28 %U, Uuid: ⸮R<x⸮⸮K⸮%
Searching: 
226478
Receiving: 258 ,18.16 °C, 63.32 %U, Uuid: ⸮R<x⸮⸮K⸮%
Searching: 
228498

Thank you Luca

**Comment by KrisKasprzak** [comment]
still not much for me to go on, wiring diagram, ino file. Try sending/receiving without the library. You only really need this library to program these EBYTE units. For reading data structures, you can call readBytes directly on the EBYTE Serial object

ESerial.readBytes((uint8_t*)& MyData, (uint8_t) sizeof(MyData));

for writing data structures you can call write directly on the EBYTE Serial object

ESerial.write((uint8_t*) &Data, PacketSize );
