### ISSUE TITLE
Hi there, problems using the library with E22-400T30S

### ISSUE THREAD

**Issue by StanleyLG** [KrisKasprzak/EBYTE#5]
Hi, I have 2 pieces of E22-400T30S using 1W SMD wireless modules and I'm trying to figure out how these 2 can communicate. Even if I have set the address and things like that, I do not see the changes been made into the configurations. Is it possible if you could share more about how to use the library? Thanks.

**Comment by KrisKasprzak** [comment]
It would help to know what MCU's you have, your code, wiring setup, etc. Not much I can do with the inf provided.
