### ISSUE TITLE
Delivery confirmation E220 

### ISSUE THREAD

**Issue by Yousefff1** [KrisKasprzak/EBYTE#53]
Hi @KrisKasprzak,

Is there any way that E220 would know if the transmitted message was delivered? I've been doing some research on this and it seems there is not.

I am currently using a very crude way to ensure delivery:

- Transmitter sends a message, and listens for a reply, entering a while with a loop, it keeps sending the data every 20 seconds and listening.  
- Receiver receives the message and sends the confirmation.
- Once the sender gets the confirmation it breaks the while statement and goes to sleep.

Thank you so much for your help!!

**Comment by KrisKasprzak** [comment]
You logic is about the only way to know if a message was received.

 

    On Thursday, March 31, 2022, 09:44:29 AM CDT, Yousefff1 ***@***.***> wrote:  
 
 


Hi @KrisKasprzak,

Is there any way that E220 would know if the transmitted message was delivered? I've been doing some research on this and it seems there is not.

I am currently using a very crude way to ensure delivery:
   
   - Transmitter sends a message, and listens for a reply, entering a while with a loop, it keeps sending the data every 20 seconds and listening.
   - Receiver receives the message and sends the confirmation.
   - Once the sender gets the confirmation it breaks the while statement and goes to sleep.

Thank you so much for your help!!

**Comment by KrisKasprzak** [comment]
There is no way to know automatically. Doing this manually would require sending a confirmation back after receiving a message. This is not technically difficult, on the transmitter side, once a message is sent, start listening for a reply. You should add some type of timer to keep the listen from waiting forever.
