### ISSUE TITLE
Backwards compatability issues Ebyte E32-900T20D to E32-868T20D

### ISSUE THREAD

**Issue by Oldmaker49** [KrisKasprzak/EBYTE#54]
This is an issue I have raised with EBBYTE. 
Legacy  E32-868T20D modules (no longer available) have compatibility issues with the replacement E32-900T20D V8.1 modules.
I have been advised by EBYTE that they will only communicate with Air Data Rate of 9600kbps. I have tested this and when the 868 is the Tx and the 900 the Rx it works. But there is some problems when the 900 transmits to the 868. I raised this with EBYTE and they recommend only using E32-900T20D together. 
This is a problem when expanding existing legacy systems since the E32-868T20D is no longer available.

**Comment by KrisKasprzak** [comment]
not sure what I can do here. closing.

**Comment by Oldmaker49** [comment]
Hi Kris,

For information only



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
