### ISSUE TITLE
Receiver power in real time with Ebyte E32 900T30D

### ISSUE THREAD

**Issue by DARXS** [KrisKasprzak/EBYTE#69]
Hi Kris Kasprzak
 
I have ebyte e32 900t30d LoRa modules and I would like to know how to acquire the receiver power in real time at certain distances and if it is possible to acquire the path loss exponent?

**Comment by KrisKasprzak** [comment]
I have these same modules, and assuming you are referring to RSSI, unfortunately, they aren't capable of providing that information.
