### ISSUE TITLE
Ebyte E07-433M20S Pa Table

### ISSUE THREAD

**Issue by jamesbit** [KrisKasprzak/EBYTE#71]
Hi all !

I have an E07-433M20S module but I can’t activate 20 dbm output.

I Use Arduino Nano and the LSatan SmartRC-CC1101-Driver-Lib-master library.

Could someone tell me if there is a way to activate a 20 dbm mode or how can I modify the SmartRC-CC1101-Driver-Lib-master library to obtain a PA Table that supports the power of 20 dbm ?

Thank you.

James.

**Comment by KrisKasprzak** [comment]
This library does not support that SPI module. This inquiry should be posted on the libraries issue page.
