### ISSUE TITLE
Arduino Uno

### ISSUE THREAD

**Issue by JayZeeM** [KrisKasprzak/EBYTE#72]
Im using Arduino Uno where the rx is 0 pin and tx is 1 pin. Do you have any sample codes for using Arduino Uno? and sample picture of connection. Thank you!

**Comment by KrisKasprzak** [comment]
I hope you are not using pin 0 or 1, those are reserved for USB connection. You must use Software Serial.

Look in the examples section of the EBYTE library for an arduino example.

Note arduinos are 5 volt devices and the pins on the EBYTE are 3.3 but 5 volt tolerant. Yoy may need some series resistors or pullups.

**Comment by KrisKasprzak** [comment]
This may help as well

https://youtu.be/hMjArKGucFA?si=uJ7buEbnHgXTsLtC
