### ISSUE TITLE
RSSI and FEC

### ISSUE THREAD

**Issue by JayZeeM** [KrisKasprzak/EBYTE#74]
Hello Im seeing the RSSI in the parameters how can I print the RSSI value? and how to assure if the FEC is working?

**Comment by JayZeeM** [comment]
I am using E22 900T22D

**Comment by KrisKasprzak** [comment]
This library does not support newer modules with RSSI capability.

**Comment by KrisKasprzak** [comment]
Have a look at RadioHead's lib, that one may support RSSI.

**Comment by JayZeeM** [comment]
Is it ok to use two libraries?
