### ISSUE TITLE
Setting FEC

### ISSUE THREAD

**Issue by JayZeeM** [KrisKasprzak/EBYTE#78]
Hello! Im trying to activate the FEC for my EByte E22 using

  Serial.print(Transceiver.SetFECMode(1));

but I'm getting an error
![image](https://github.com/KrisKasprzak/EBYTE/assets/155596287/1ecc5459-5088-4ad8-9b42-77f82346c893)

**Comment by KrisKasprzak** [comment]
That function does not return anything, so you can’t print anything. Have a look at the.H file.
