### ISSUE TITLE
Examples and comments

### ISSUE THREAD

**Issue by tqueale** [KrisKasprzak/EBYTE#8]
Your supplied examples contain NO comments! 
Please add copious comments explaining exactly what you are doing and why.
Also, as these units are both send and receive, please consider an example of a half-duplex bi-directional link (with comments of course). This would seem to be a common requirement with most comms requiring some form of acknowledgement.

**Comment by Hubaxis7** [comment]
Yes, I also need two-way communication with the addresses of the receivers and recipients.
For example, I need to transfer data to LoRa modules (4 pieces) with the address 128. And get a response from them to the module with the address 120. I do not understand how to set the address of the data recipient.

**UPDATE**
I found on the [EBYTE](http://www.ebyte.com/en/program.aspx#leval-menu#leval-menu) website a little explanation of how to send data to a specific address and channel. 
![2016828140229511](https://user-images.githubusercontent.com/22938004/66315223-098c6f80-e91e-11e9-95d3-0825e498eb21.png)
![2017261534336694](https://user-images.githubusercontent.com/22938004/66315224-098c6f80-e91e-11e9-8016-e79f50c1498e.jpg)
![2017261558134975](https://user-images.githubusercontent.com/22938004/66315226-0a250600-e91e-11e9-9ba6-2fd983800caf.jpg)

There are other libraries on github that implement sending to any specified address.
