### ISSUE TITLE
overflow problem and transmitting two or more struct instead one

### ISSUE THREAD

**Issue by RafaelFerrari95** [KrisKasprzak/EBYTE#80]
hi @KrisKasprzak 

It's me again, I tried to edit my text from the previous problem, but I could only edit the title (I'm new to Github and still discovering the platform's features).

i have a few more question that i don't put in my previous problem

1)
the overflow problem could be solved cleaned the buffer? i studied datasheet of ebyte E32 and the TX lenght is 58 byte which is the maxium byte in a packeage and my struct is with 53 byte. so the lora ebyte should transmitting the struct with out problemns, correct?

2) in my new skecth i tried do transmitting only the "count" with a delay 100ms and works fine, but if decreasiing this delay to 90ms occur the overflow. why?

3) what is the solution about this overflow? change the air dates?
 
4)
i tried to transmitting two structs and the lora reception will exhibit one in void setup and other in void loop. the void loop shows ok, but the struct that would be exhibit in setup doesn't appears, why? i tried to reset the esp receptor and esp transmissor but not work :/

thank you for your time and consideration

**Comment by KrisKasprzak** [comment]
I’m not sure what you mean by overflow problem are you getting updated no data?

You’re not limited to 58 bytes. Your struct can be less or more. As soon as you stop sending data to the EBYTE for more than 2 ms that’s when it sends its data. The receive on the other side will build the structure when it has all the data.

reduce the delay. Time is probably corrupting your data in error. These things aren’t the fastest in the world tried increasing your air data rate however that will decrease transmit distance.

you should be able to send two completely different struts, but make sure the first one was received before you exit set up.
