### ISSUE TITLE
Can't Receive data even with correct configurations. 

### ISSUE THREAD

**Issue by knowOne08** [KrisKasprzak/EBYTE#81]
Hello kris,

I am using 2 E32-900T30D with esp8266 to send and receive data, But the on the receivers side the control never enters 
               
               if(ESerial.available())
               
![Screenshot from 2024-04-12 01-10-48](https://github.com/KrisKasprzak/EBYTE/assets/117254962/086a15a6-62cd-4843-86dc-c4ab919127a4)

Is there something wrong that i am doing ?

**Comment by KrisKasprzak** [comment]
I’m going to need more detail than this. Are both MCU the same? How is the receiver wired up and transmitter wired up? 99 of Time TX is connected to TX. And how are these being powered?

**Comment by knowOne08** [comment]
Yes both the MCUs are same both are NodeMCUs

All the connections are according to the comments of the  example code

They are powered with 3v out of NodeMCU

**Comment by KrisKasprzak** [comment]
Caution on powering the EBYTE with the onboard regulator. These 30 DB units can draw near an amp and can destroy the regulator--power them separately. Is this the issue? Maybe not but a place to start.

**Comment by knowOne08** [comment]
Yes we've powered with external 3.7v LiPo also, still doesn't work.

**Comment by KrisKasprzak** [comment]
I have these same EBYTE units working with 2 x ESP8266 MCU.  

Mine fire right up and transmit.  I have my EBYTE's  powered from an external power supply capable of supply enough current. My units were drawing < 1 amp. Transmission worked with EBYTE power supply from 3v3 up to 5v0.

Note I had to tie ALL grounds together to get the transmission to work.

Unless you send a picture or accurate wiring diagram, I'm not sure what else I can say. 

![image](https://github.com/KrisKasprzak/EBYTE/assets/20391565/874ff5d9-631c-4dcd-b6b1-202ec1456a7d)

**Comment by KrisKasprzak** [comment]
Since you are able to GetParameters(), your pin definition is probably correct. For future reference on these ESP's the pins are not what you set in the pin definition D2 is not 2...

I liberated this from a post that shows the mapping.

static const uint8_t D0   = 16;
static const uint8_t D1   = 5;
static const uint8_t D2   = 4;
static const uint8_t D3   = 0;
static const uint8_t D4   = 2;
static const uint8_t D5   = 14;
static const uint8_t D6   = 12;
static const uint8_t D7   = 13;
static const uint8_t D8   = 15;
static const uint8_t D9   = 3;
static const uint8_t D10  = 1;

Silly I know, not sure why ESP makers can be consistent :(

**Comment by knowOne08** [comment]
I am currently not  having the modules with me I will definelty post the connections  picture tommorow. 

But we also tried testing the modules with EMF meteres to see the modules were broken but both the modules showed readings on EMF reader when powered on ?

Can the hardware still have a any other problem?

PS: We also downloaded the RF settings software that the EByte provides but there is no specific one for E32-900T30D so we downloaded a general one (last fourth one on [this](https://www.ebyte.com/en/data-download.html?page=3&id=199&cid=31#load) page) . When we connected the  module with FTDI and ran  GetParams from software, it said "No Response from modul"

**Comment by knowOne08** [comment]
I knew I would have been doing some silly mistake. 

The UART data rate was 0/0/0 (1200 bauds) and I was using 9600 baud  you can see in the screenshot I gave earlier.  

I just   added Transceiver.SetUARTBaudRate(UDR_9600); and it works :joy:
